FROM node:18-slim

WORKDIR /app

COPY . .

RUN npm install -g npm@9

# Install node dependencies
RUN CI=true npm ci --ignore-scripts 

# Build
RUN npm run build --workspace packages/core
RUN npm run build --workspace apps/api

# Environment
ENV NODE_ENV=production
ENV NODE_OPTIONS="--enable-source-maps"
# Fastify throws WAY to many of these warnings
ENV NODE_NO_WARNINGS=1 
ENV HOST=0.0.0.0

ENV PATH=$PATH:/app/bin

USER node

CMD ["node", "./apps/api/dist/server.js"]
